In [3]:
import os              # working directory 
import pandas as pd    # data preprocessing
import numpy as np     # data preprocessing
import math            # using mathematical functions
import seaborn as sns            # for visualization
import matplotlib.pyplot as plt  # for visualization
from plotly.offline import init_notebook_mode, iplot   # for visualization
from pandas.plotting import scatter_matrix             # for visualization
from IPython.display import display, HTML              # for html & display
import warnings  
%matplotlib inline

pd.options.display.max_columns = None   #999  
pd.options.display.max_rows = None      #999    
pd.options.display.float_format = '{:.2f}'.format
warnings.filterwarnings("ignore")  
init_notebook_mode(connected=True)

# for css style of dataframe
from IPython.display import HTML
import pandas as pd


#################### USING sticky header and index ####################
#### generate DataFrame ####
# >>> df


# set style
style = """
    <style scoped>        
        .dataframe-div {
          max-height: 300px;
          overflow: auto;      // scroll bar
          position: relative;
        }
        
        .dataframe thead th {
          position: -webkit-sticky; /* for Safari */
          position: sticky;
          top: 0;
          background: black;
          color: white;
        }

        .dataframe thead th:first-child {
          left: 0;
          z-index: 1;
        }

        .dataframe tbody tr th:only-of-type {
                vertical-align: middle;
        }

        .dataframe tbody tr th {
          position: -webkit-sticky; /* for Safari */
          position: sticky;
          left: 0;
          background: black;
          color: white;
          vertical-align: top;
        }
    </style>
"""

# concatenate to single string
# >>> df = style + '<div class="dataframe-div">' + df.to_html() + "\n</div>"


# Displaying DataFrame
# >>> HTML(df)
#################################################################################

#### usage ####
# df_name = 'DataFrame that you generated while coding'
# HTML(style + '<div class="dataframe-div">' + df_name.to_html() + "\n</div>")

# basic init. phrase
data = { 'col_01' : ['1a', '2b', '3c'],
         'col_02' : ['a', 'b', 'c'],
         'col_03' : [100, 200, 300] }
df = pd.DataFrame(data)
HTML(style + '<div class="dataframe-div">' + df.to_html() + "\n</div>")

<hr>

# pandas

## 3 data structures in pandas
 - Series
 - DataFrame
 - Panel

In [4]:
import pandas as pd

## Series
 - consists of : index & value

In [5]:
sr = pd.Series([17000,18000,1000,5000],
               index=["pizza","chicken","coke","beer"])
sr

pizza      17000
chicken    18000
coke        1000
beer        5000
dtype: int64

In [6]:
sr.values

array([17000, 18000,  1000,  5000], dtype=int64)

In [7]:
sr.index

Index(['pizza', 'chicken', 'coke', 'beer'], dtype='object')

In [8]:
print("value of series :", sr.values)
print("index of series :", sr.index)

value of series : [17000 18000  1000  5000]
index of series : Index(['pizza', 'chicken', 'coke', 'beer'], dtype='object')


## DataFrame
 - 2 dimensional data structure
 - consists of : columns & index & values
 - column : column-direction index
 - index : row-direction index

In [9]:
values_input = [[1,2,3],[4,5,6],[7,8,9]]
index_input = ['one', 'two', 'three']
columns = ['A', 'B', 'C']

df = pd.DataFrame(values_input, index=index_input)
df

0  1  2
one    1  2  3
two    4  5  6
three  7  8  9

In [10]:
df.index

Index(['one', 'two', 'three'], dtype='object')

In [11]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int64)

Define DataFrame
 - using List

In [12]:
# Define DataFrame using List

data = [
    ['1000', 'Kay', 90.72],
    ['1001', 'Jay', 78.09],
    ['1002', 'Dee', 98.43],
    ['1003', 'Zet', 64.19],
    ['1004', 'Pee', 81.30]
]
df = pd.DataFrame(data)
df

0    1     2
0  1000  Kay 90.72
1  1001  Jay 78.09
2  1002  Dee 98.43
3  1003  Zet 64.19
4  1004  Pee 81.30

In [13]:
# set column name of dataframe
df = pd.DataFrame(data, columns=['no','name','score'])
df

no name  score
0  1000  Kay  90.72
1  1001  Jay  78.09
2  1002  Dee  98.43
3  1003  Zet  64.19
4  1004  Pee  81.30

In [14]:
# Define DataFrame using Dictionary

data = {'no' : ['1000', '1001', '1002', '1003', '1004', '1005'],
        'name' : ['Bee','Cee','Dee','Eee','Eff','Gee'],
        'score' : [90.72, 78.09, 98.43, 64.19, 81.30, 99.14]}
df = pd.DataFrame(data)
df

no name  score
0  1000  Bee  90.72
1  1001  Cee  78.09
2  1002  Dee  98.43
3  1003  Eee  64.19
4  1004  Eff  81.30
5  1005  Gee  99.14

Value Indexing in DataFrame
 - df.head()
 - df.tail()
 - df['column_name']

In [18]:
df.head(2)

no name  score
0  1000  Bee  90.72
1  1001  Cee  78.09

In [19]:
df.tail(2)

no name  score
4  1004  Eff  81.30
5  1005  Gee  99.14

In [20]:
df['no']

0    1000
1    1001
2    1002
3    1003
4    1004
5    1005
Name: no, dtype: object

### Redading data
 - pandas supports csv, txt, excel, sql, html, json file

In [33]:
# df = pd.read_csv('test.csv')
# df

# numpy

In [21]:
import numpy as np

In [23]:
a = np.array([1,2,3,4,5])  # using list to make 1 dimension array
type(a)

numpy.ndarray

In [24]:
a

array([1, 2, 3, 4, 5])

In [25]:
b = np.array([[10,20,30], [60,70,80]])
b

array([[10, 20, 30],
       [60, 70, 80]])

In [31]:
print('dimension of array :', b.ndim)

dimension of array : 2


In [32]:
print('shape of array :', b.shape)

shape of array : (2, 3)
